services:
  sql-server:
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" &>/dev/null
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s