version: '3.8'

services:
  # SQL Server Service
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "1433:1433"
    networks:
      - torneo-network
    volumes:
      - sql-data:/var/opt/mssql/data

  # Frontend Service
  torneo-app:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - torneo-network
    depends_on:
      sql-server:
        condition: service_started

  app:
    image: ${DOCKER_USERNAME}/torneo-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-server
    environment:
      - ConnectionStrings__IdentityDataContextConnection=Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};MultipleActiveResultSets=true;Encrypt=False
    networks:
      - torneo-network

networks:
  torneo-network:

volumes:
  sql-data: