version: '3.8'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" &>/dev/null
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - torneo-network

  torneo-app:
    container_name: torneo-app
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true
    ports:
      - "5000:80"
    depends_on:
      - sql-server
    networks:
      - torneo-network

networks:
  torneo-network:
    driver: bridge

volumes:
  sqldata: