# CI configuration for GitHub Actions
version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" &>/dev/null
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - torneo-network

  torneo-app:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - torneo-network

networks:
  torneo-network:
    driver: bridge