# Production configuration for Render
version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - torneo-network

  torneo-app:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true
    depends_on:
      - sql-server
    networks:
      - torneo-network

networks:
  torneo-network:
volumes:
  sqldata: