version: '3.9'

services:
  torneo-app:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "3000:80"
    depends_on:
      - sql-server

  # Backend Service
  # torneo-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-Backend
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - sql-server

  # Database Service
  sql-server:
    image: "microsoft/mssql-server-linux:2019-latest"
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWOR}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql/data
    networks:
      - torneo-network
volumes:
  sql-data: