version: '3.9'

services:
  # SQL Server Service
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
      MSSQL_TCP_PORT: "${MSSQL_TCP_PORT}"
    ports:
      - "1433:1433"
    hostname: sql-server
    container_name: sql-server
    volumes:
      - sql-data:/var/opt/mssql/data
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - torneo-network
  
  # Frontend Service
  torneo-app:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - torneo-network
    depends_on:
      "sql-server":
        condition: service_started

  app:
    image: ${DOCKER_USERNAME}/torneo-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings_IdentityDataContextConnection=Server=db;Database=Torneo;User Id=sa;Password=admin123;MultipleActiveResultSets=true;Encrypt=False

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"