services:
  torneo-app:
    container_name: torneo-app
    build:
      context: ./app
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    networks:
      - torneo-network

networks:
  torneo-network:
    driver: bridge

volumes:
  sqldata: