services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: oregon
    branch: qa
    dockerfilePath: ./Dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: PORT
        value: 80
    healthCheckPath: /health

# Exported from Render on 2024-12-24T10:39:42Z
databases:
- name: DB-Tournament-Management-App
  databaseName: torneo_w6fq
  user: sa
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
