services:
  - type: web
    name: tournament-management-app
    env: docker
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true
      - fromGroup: sql-server-config
    
  - type: pserv
    name: sql-server
    env: docker
    region: ohio
    image:
      url: docker.io/microsoft/mssql-server-linux:2019-latest
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        sync: false