services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: ohio
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: sh /app/publish/startup.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true