services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    branch: qa
    dockerfilePath: ./Dockerfile
    dockerCommand: docker-compose -f docker-compose.prod.yml up
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true