services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: oregon
    branch: qa
    dockerfilePath: ./app/Dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      ASPNETCORE_ENVIRONMENT: Production
      MSSQL_SA_PASSWORD:
        sync: false
      PORT: 80
    healthCheckPath: /health
    autoDeploy: true

  - name: mssql-db
    type: web_service
    env: docker
    dockerfilePath: ./db/Dockerfile
    region: oregon
    plan: free
    branch: qa
    envVars:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
    healthCheckPath: /
    autoDeploy: true
