services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    branch: qa
    dockerfilePath: ./Dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: PORT
        value: 80
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: tournament-db
          property: connectionString

  - type: pserv
    name: tournament-db
    env: docker
    plan: free
    branch: qa
    image: 
        url: mcr.microsoft.com/mssql/server:2019-latest
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: MSSQL_SA_PASSWORD
        sync: false    