services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: oregon
    branch: qa
    dockerfilePath: ./Dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: PORT
        value: 80
      - key: ConnectionStrings__DefaultConnection
        value: "Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true"
    healthCheckPath: /health