services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: starter
    region: ohio
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t tournament-app .
    startCommand: docker run tournament-app
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - fromGroup: sql-server-config
    
  - type: pserv
    name: sql-server
    env: docker
    plan: starter
    region: ohio
    repo: https://hub.docker.com/_/microsoft-mssql-server    
    disk:
      name: data
      mountPath: /var/opt/mssql
      sizeGB: 5
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        generateValue: true