services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - fromGroup: sql-server
  
  - type: pserv
    name: sql-server
    env: docker
    image:
        url: mcr.microsoft.com/mssql/server:2019-latest    
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        generateValue: true