services:
  - type: web
    name: tournament-management-app
    env: docker   
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: MSSQL_SA_PASSWORD
        sync: false
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql-server;Database=Torneo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true

  - type: pserv
    name: sql-server
    env: docker    
    image:
        url: mcr.microsoft.com/mssql/server:2019-latest
    disk:
      name: data
      mountPath: /var/opt/mssql
      sizeGB: 10
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        sync: false