services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: starter
    region: ohio
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: sh /app/publish/startup.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MSSQL_SA_PASSWORD
        sync: false
      - fromGroup: sql-server
    
  - type: pserv
    name: sql-server
    env: docker
    plan: starter
    region: ohio
    image: mcr.microsoft.com/mssql/server:2019-latest
    disk:
      name: data
      mountPath: /var/opt/mssql
      sizeGB: 10
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: SA_PASSWORD
        generateValue: true