services:
  - type: web
    name: tournament-management-app-sqlite
    env: docker
    plan: free
    region: oregon
    branch: qa-sqllite-optimization
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Staging
      - key: PORT
        value: "80"
    healthCheckPath: /health
    autoDeploy: true
    mounts:
      - type: volume
        target: /app/Torneo.db
      - type: volume
        target: /root/.aspnet/DataProtection-Keys
