services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: oregon
    branch: qa
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Staging 
      - key: PORT
        value: "80"
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: mssql-db
    env: docker
    dockerfilePath: ./db/Dockerfile
    dockerContext: ./db
    region: oregon
    plan: free  
    branch: qa
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SA_PASSWORD
        value: "${MSSQL_SA_PASSWORD}"
      - key: MSSQL_PID
        value: Developer
      - key: PORT
        value: "1433"
      - key: MSSQL_MEMORY_LIMIT_MB
        value: "512"
      - key: MSSQL_MIN_MEMORY_LIMIT_MB
        value: "128"
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 70
    healthCheckPath: /health
    autoDeploy: true
