services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerCommand: docker-compose -f docker-compose.prod.yml up