services:
  - type: web
    name: tournament-management-app
    env: docker
    plan: free
    region: oregon
    branch: qa
    dockerfilePath: ./app/Dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: qa
      - key: MSSQL_SA_PASSWORD
        valueFromSecret: mssql-sa-password
      - key: PORT
        value: 80
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: mssql-db
    env: docker
    dockerfilePath: ./db/Dockerfile
    region: oregon
    plan: free
    branch: qa
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SA_PASSWORD
        valueFromSecret: mssql-sa-password
      - key: MSSQL_PID
        value: Developer
    healthCheckPath: /
    autoDeploy: true
