name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test Frontend
        working-directory: .
        run: |
          docker-compose build --env-file .env
          docker-compose --env-file .env up -d 
          docker-compose run --rm torneo-app dotnet test --configuration Release --no-build
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://localhost:80
      
      - name: Test database
        working-directory: Torneo.App/Torneo.App.Frontend
        run: |
          docker-compose run --rm torneo-app dotnet ef database update --configuration Release --no-build
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://localhost:80

      # - name: Build and Test Backend
      #   working-directory: Torneo.App.Backend
      #   run: |
      #     docker-compose build
      #     docker-compose up -d
      #     docker-compose run --rm backend dotnet test --configuration Release --no-build
      #   env:
      #     ASPNETCORE_ENVIRONMENT: Development
      #     ASPNETCORE_URLS: http://localhost:80


      - name: Stop containers
        run: docker-compose down

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            Torneo.App.Frontend/TestResults
            # Torneo.App.Backend/TestResults

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: |
            Torneo.App.Frontend/coverage
            # Torneo.App.Backend/coverage
      
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            Torneo.App.Frontend/logs
            # Torneo.App.Backend/logs
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            Torneo.App.Frontend/artifacts
            # Torneo.App.Backend/artifacts
      
      - name: Upload docker-compose logs
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose-logs
          path: |
            Torneo.App.Frontend/docker-compose-logs
            # Torneo.App.Backend/docker-compose-logs
