name: Build and deploy ASP.Net Core app to Render.com

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build with dotnet
        working-directory: ./Torneo.App
        run: dotnet build Torneo.App.sln --configuration Release

      - name: Publish with dotnet
        working-directory: ./Torneo.App
        run: dotnet publish Torneo.App.sln -c Release -o out

      - name: Build Docker image        
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/torneo-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAM }}/torneo-app:latest      
      
      - name: Install EF Tools
        run: |
          dotnet tool install --global dotnet-ef --version 6.0.0
          
      - name: Build and Test
        run: |
          dotnet restore Torneo.App/Torneo.App.sln
          dotnet build Torneo.App/Torneo.App.sln
          
      - name: Create Migration Script
        run: |
          cd Torneo.App/Torneo.App.Persistencia
          dotnet ef migrations script -o init.sql --idempotent
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
          
      - name: Build Docker images
        run: |
          docker-compose build
        env:
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
      
      - name: Run Docker Compose
        run: |
          docker-compose up -d sql-server
          sleep 30
          docker-compose up -d torneo-app
        env:
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          
      - name: Wait for services to be healthy
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/health)" != "200" ]]; do sleep 5; done' || false

      - name: Deploy with Docker Compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        run: docker-compose up -d       
  

      

# deployment steps for Render
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Render.com
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceId": "srv-ctid1c8gph6c738524e0",
            "branch": "qa"
          }' \
          https://api.render.com/v1/services/srv-ctid1c8gph6c738524e0/deploys